<?php $this->load->view('header'); ?>
<style>



</style>


<div class="container-fluid mt-3" style="padding: 6%">

  <div class="row mb-3">
    <h2>Update Study Group </h2>
    <p>U<p><em>Update Study Group</em> (erstwhile &lsquo;Update&rsquo;) began publication from Kolkata, India in 1999. From the very beginning, &lsquo;Update&rsquo; stood for international socialist movement and Marxist world outlook. &lsquo;Update&rsquo; analysed data and resources and published those materials from radical perspectives. Till now twenty-one series of &lsquo;Update&rsquo; were published. Considerable numbers of political and social activists used the data and analysis presented in &lsquo;Update&rsquo; in the last two decades. Moreover, three pamphlets were published in Bengali highlighting the condition of adivasis (tribals) of India, the mass-struggle against totalitarianism in the Middle East and on question on developing class struggle in India.</p>
<p>Since 2015, &lsquo;Update&rsquo;, now functioning as <em>Update Study Group</em>, delved into deeper questions and problems of prospects of Indian revolution and international socialist movement from a broader perspective. It is now searching, analysing and working on several questions of national and international importance. We have authored two books: &lsquo;Condition of the workers in Asia&rsquo;, and &lsquo;Sangh Parivar and Hindutvavad: Basis, Genesis and Development&rsquo; (in Bengali). We have made initial searches finding the relation between the emergence of covid-19 pandemic and capitalism.</p>
<p>In the present situation, particularly in the last four/five decades, the international capital, dipped into stagnation and recurrent crisis, had an urgent need to find new avenues of investing the surplus generated to maximise the profits. Under the name of globalisation, the international capital has taken the course of financialisation and made deeper inroads in the Global South to tap the investment prospects. In fact, with the neoliberal agenda pioneered under the aegis of Reagonomics and Thatcherism and with the infamous ideology of Milton Friedman, the international capital has unleashed continuous onslaughts on the world proletariat. With the neoliberal mantra of globalisation, the late capitalism dismantled the Keynesian welfare models in the Global North; snatched the hard-own rights of the workers of the countries, and bribed the reformist leaders of the working class movement. In this process they succeeded till date to make international working class movement mostly rudderless and demoralised. Such efforts were particularly accelerated after the dismantling of the so-called socialist powers in the USSR and Eastern Europe and with the great leap of China along capitalist path. It is to be noted in this context that the long-standing internal weakness in the international socialist movement is primarily the most important factor behind the retrogressive trends in the class struggle of the proletariat in both national and international plane. Therefore, the resurgence and revitalisation of the international socialist movement is an urgent task in the present moment.</p>
<p><em>Update Study Group</em> studied that at present, the international capital made far-reaching inroads into the economies of Global South. In this process, it opened the scope of exploiting the cheap labour and cheap land of the Global South to make super profits to an unprecedented level; plundered the natural resources; and with the strengthening of global supply chains of production, they somewhat altered the method of exploitation of the cheap labour and cheap land of the Global South. The neoliberal imperialist projects of the World Bank, International Monetary Fund and World Trade Organisation made these advances easier and severely detrimental to the workers, peasants and poor people of the Global South. These institutions, either by forcing the ruling classes of the Global South or by taking advantage of these classes&rsquo; strong link with global capital made them swallow the pills of structural adjustment programme. The processes of neoliberal reforms through privatisation, deregulation and dismantling of the public utilities and services are accelerated in these countries. In effect, the imperialist stranglehold on the people of the Global South is vastly consolidated and tightened.</p>
<p><em>Update Study Group</em> is well aware of the fact that during the last few decades, the global capital pushed the earth to the brink of disaster by disrupting and destroying the ecology and nature. The capitalist system &lsquo;gifted&rsquo; global warming, climate change, natural disasters in the form of floods, droughts, recurrent cyclonic storms, bushfires, rising of the sea water level due the fast melting of glaciers, imminence of submerging of several islands and coastline cities, gradual extinction of several species, increasing spillover of viruses from wild and domesticated animals on to humans. In effect, the capitalism created an irreparable &lsquo;metabolic rift&rsquo; between the nature and capitalist society accelerating the process of destruction of the life on the planate.</p>
<p>In the Indian plane, <em>Update Study Group</em> has noted several striking features which must be counted in the course of rekindling the socialist movement. In India, the conditions of the peasants and agrarian labours are continuously degrading under the collective exploitative system of capitalism and remnants of feudalism which are tightly integrated with the imperialism. Each year thousands of peasants commit suicides. Most of the lands are concentrated in the few hands of rural landlords and rich peasants, making a sea of landless peasants and agrarian workers with meagre resources and jobs. Moreover, series of privatisations and deregulations, retrenchments, cutting the benefits, and state-terror unleashed on the workers to suppress their efforts in organising their own trade unions plague the lives of the workers of the country. Staggering unemployment and underemployment; abysmal poverty and inequality; chronic undernourishment; poor state of public health system and lack of proper medication for the penniless; illiteracy and little opportunities of higher education for the poor; utterly inadequate and continually squeezed relief measures from the successive governments; prolonged starvation and starvation-deaths, etc. are part and parcel of the Indian poor people. In this situation, the march of the neoliberal capitalist onslaughts is going on mostly unopposed.</p>
<p>It is noted by <em>Update Study Group</em> that the development of class-struggle of the proletariat and the struggle for emancipating itself from the capitalist exploitation were paralysed for long due to the presence of strong reformist current in the ranks of the working class and due to the immanent weakness in building of class-consciousness among the proletariat in India. In fact, the building of the class struggle mostly depends upon question of defeating this reformist trends in the ranks of the proletariat. It is notable that the question of agrarian and/or democratic revolution in the country is pushed to back in recent decades. Moreover, due to the presence of vast feudal remnants and omnipotence of old values/customs in the country, the Dalits are forced to live in utterly dehumanising conditions under oppressive regimes of upper castes. The so-called backward castes &ndash; though the conditions of them are relatively better than Dalits &ndash; regularly stigmatised at the behest of the upper castes. Adivasis or the &lsquo;tribal&rsquo; people are indiscriminately deprived, dispossessed and oppressed by the upper echelons of the society &ndash; the wealthy and the capitalists. The country is still regarded as a prison of oppressed nationalities. The religious minorities are routinely victimised and terrorised. It is notable that the Dalits, backward castes, Muslims, and Adivasi constitute the overwhelming majority of the working people of India. Moreover, the question of emancipation of the women &ndash; the half of the society &ndash; is becoming more burning in today&rsquo;s India. But, the rights of speech, protest and organisation are continually undermined in present-day India under oppressive measures on behalf of the state. Old hackneyed, unscientific and irrational outlooks are preached with unforeseen rapidity. Hindutvavadi fascist ideologies and organisations are gripping the society with great momentum. As a whole, the organs of the state are gravitating towards fascist vortex.</p>
<p>Under the context, <em>Update Study Group</em> is earnestly involved in searching and analysing the present situation with critical outlook and Marxist vision. It is expected that the online <em>Update Study Group</em> will serve as a website for critical analysis of the existing system and become a radical platform in building the movement for a socialist and ecologically sustainable society.</p></p>
    

  </div>




</div>



<?php $this->load->view('footer'); ?>